# Étape 1 : builder l'app avec Node
FROM node:18-alpine AS builder
WORKDIR /app

# Installer les dépendances
COPY package*.json ./
RUN npm ci

# Copier tout et lancer le build
COPY . .
ARG VITE_API_URL
ENV VITE_API_URL=${VITE_API_URL}
RUN npm run build

# Étape 2 : image de prod Nginx pour servir le build
FROM nginx:stable-alpine AS runner
WORKDIR /etc/nginx/conf.d

# On remplace la conf par défaut par la nôtre
COPY nginx.conf default.conf

# On copie le build dans le dossier servi par Nginx
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
